import {
  Document as DocxDocument,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  TableOfContents,
  Header,
  Footer,
  PageNumber,
  AlignmentType,
  BorderStyle,
  convertInchesToTwip,
  ExternalHyperlink,
  UnderlineType
} from "docx";
import pptxgen from "pptxgenjs";
import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";

export interface AssembleSection {
  title: string;
  brief: string;
  content: string;
  keyPoints?: string[];
}

export interface AssembleDocumentInput {
  title: string;
  subtitle: string;
  author?: string;
  format: "docx" | "pptx" | "xlsx" | "pdf";
  sections: AssembleSection[];
}

/**
 * Parses Markdown paragraphs and transforms embedded citations
 * like [Source: Title](https://...) into real Word ExternalHyperlink nodes.
 */
function parseParagraphRunsWithHyperlinks(rawText: string): Array<TextRun | ExternalHyperlink> {
  const elements: Array<TextRun | ExternalHyperlink> = [];
  const linkRegex = /\[([^\]]+)\]\((https?:\/\/[^\s\)]+)\)/g;
  let lastIndex = 0;
  let match;

  while ((match = linkRegex.exec(rawText)) !== null) {
    const textBefore = rawText.slice(lastIndex, match.index);
    if (textBefore) {
      elements.push(
        new TextRun({
          text: textBefore,
          size: 24, // 12pt
          font: "Plus Jakarta Sans",
          color: "1B1C1A"
        })
      );
    }

    const anchorText = match[1];
    const linkUrl = match[2];

    elements.push(
      new ExternalHyperlink({
        children: [
          new TextRun({
            text: `[${anchorText}]`,
            size: 24,
            font: "Plus Jakarta Sans",
            color: "97422C",
            bold: true,
            underline: { type: UnderlineType.SINGLE, color: "97422C" }
          })
        ],
        link: linkUrl
      })
    );

    lastIndex = match.index + match[0].length;
  }

  const textAfter = rawText.slice(lastIndex);
  if (textAfter || elements.length === 0) {
    elements.push(
      new TextRun({
        text: textAfter || rawText,
        size: 24,
        font: "Plus Jakarta Sans",
        color: "1B1C1A"
      })
    );
  }

  return elements;
}

// 1. Word Document (.docx) Assembler
export async function assembleWordDocument(input: AssembleDocumentInput): Promise<Buffer> {
  const docChildren: any[] = [];

  // Title Page & Cover
  docChildren.push(
    new Paragraph({
      text: input.title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.LEFT,
      spacing: { before: 400, after: 200 }
    }),
    new Paragraph({
      text: input.subtitle,
      style: "Subtitle",
      alignment: AlignmentType.LEFT,
      spacing: { after: 300 }
    }),
    new Paragraph({
      children: [
        new TextRun({ text: "Generated by: ", bold: true, color: "55423E" }),
        new TextRun({ text: input.author || "Paperrrrrr", italics: true, color: "97422C", bold: true }),
        new TextRun({ text: " | Date: ", bold: true, color: "55423E" }),
        new TextRun({ text: new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }) })
      ],
      spacing: { after: 500 }
    }),

    // Horizontal Rule
    new Paragraph({
      border: { bottom: { color: "DBC1BA", space: 1, style: BorderStyle.SINGLE, size: 6 } },
      spacing: { after: 400 }
    }),

    // Table of Contents
    new Paragraph({
      text: "Table of Contents",
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 300, after: 200 }
    }),

    new TableOfContents("Table of Contents", {
      hyperlink: true,
      headingStyleRange: "1-3"
    }),

    new Paragraph({ spacing: { after: 600 } })
  );

  // Sections with proper heading levels, spacing & hyperlink parsing
  input.sections.forEach((sec, idx) => {
    docChildren.push(
      new Paragraph({
        text: `${idx + 1}. ${sec.title.replace(/^\d+\.\s*/, "")}`,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 500, after: 200 }
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `Focus: ${sec.brief}`,
            italics: true,
            color: "55423E",
            size: 22 // 11pt
          })
        ],
        spacing: { after: 240 }
      })
    );

    const blocks = (sec.content || sec.brief || "").split("\n\n");
    blocks.forEach((blockText) => {
      if (!blockText.trim()) return;

      const runs = parseParagraphRunsWithHyperlinks(blockText);
      docChildren.push(
        new Paragraph({
          children: runs,
          spacing: { after: 240, line: 360 }
        })
      );
    });
  });

  const doc = new DocxDocument({
    creator: "Paperrrrrr",
    title: input.title,
    styles: {
      default: {
        document: {
          run: { font: "Plus Jakarta Sans", color: "1B1C1A" }
        }
      },
      paragraphStyles: [
        {
          id: "Title",
          name: "Title",
          basedOn: "Normal",
          next: "Normal",
          run: { font: "Georgia", size: 52, bold: true, color: "97422C" }
        },
        {
          id: "Subtitle",
          name: "Subtitle",
          basedOn: "Normal",
          next: "Normal",
          run: { font: "Plus Jakarta Sans", size: 28, italics: true, color: "55423E" }
        },
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          next: "Normal",
          run: { font: "Georgia", size: 34, bold: true, color: "97422C" }
        },
        {
          id: "Heading2",
          name: "Heading 2",
          basedOn: "Normal",
          next: "Normal",
          run: { font: "Georgia", size: 28, bold: true, color: "55423E" }
        }
      ]
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: convertInchesToTwip(1),
              bottom: convertInchesToTwip(1),
              left: convertInchesToTwip(1),
              right: convertInchesToTwip(1)
            }
          }
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                text: "Paperrrrrr Document Studio",
                alignment: AlignmentType.RIGHT,
                style: "Subtitle"
              })
            ]
          })
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun("Page "),
                  new TextRun({ children: [PageNumber.CURRENT] }),
                  new TextRun(" of "),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES] })
                ]
              })
            ]
          })
        },
        children: docChildren
      }
    ]
  });

  return await Packer.toBuffer(doc);
}

// 2. PowerPoint (.pptx) Assembler
export async function assemblePowerPoint(input: AssembleDocumentInput): Promise<Buffer> {
  const ppt = new pptxgen();
  ppt.layout = "LAYOUT_16x9";
  ppt.title = input.title;

  // Slide 1: Title Cover Slide
  const slide1 = ppt.addSlide();
  slide1.background = { color: "FAF9F5" };

  // Top Accent Bar
  slide1.addShape(ppt.ShapeType.rect, {
    x: 0.8, y: 0.8, w: 11.7, h: 0.1, fill: { color: "97422C" }
  });

  slide1.addText(input.title, {
    x: 0.8, y: 1.6, w: 11.5, h: 1.8,
    fontFace: "Georgia", fontSize: 32, color: "97422C", bold: true, wrap: true
  });

  slide1.addText(input.subtitle, {
    x: 0.8, y: 3.5, w: 11.5, h: 0.9,
    fontFace: "Arial", fontSize: 16, color: "55423E", italic: true, wrap: true
  });

  // Footer & Author
  slide1.addText(`Generated by Paperrrrrr • ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, {
    x: 0.8, y: 5.6, w: 10.0, h: 0.4,
    fontFace: "Arial", fontSize: 12, color: "88726D"
  });

  let slideCounter = 1;

  // Content Slides with Overflow Prevention and Bullet Structuring
  input.sections.forEach((sec, idx) => {
    // Break prose into distinct paragraphs / sentences for bullet formatting
    const rawParagraphs = (sec.content || sec.brief || "")
      .split("\n\n")
      .map((p) => p.trim())
      .filter((p) => p.length > 0);

    const bulletItems: string[] = [];
    rawParagraphs.forEach((para) => {
      // Clean markdown citations for clean slide reading
      const cleaned = para.replace(/\[([^\]]+)\]\([^\)]+\)/g, "$1");
      // Split into concise bullet sentences if paragraph is large
      const sentences = cleaned.split(/(?<=[.?!])\s+/);
      let currentBullet = "";
      sentences.forEach((sent) => {
        if ((currentBullet + " " + sent).length < 240) {
          currentBullet += (currentBullet ? " " : "") + sent;
        } else {
          if (currentBullet) bulletItems.push(currentBullet);
          currentBullet = sent;
        }
      });
      if (currentBullet) bulletItems.push(currentBullet);
    });

    // If bullets > 3, paginate across 2 slides so text never overflows
    const itemsPerSlide = 3;
    const totalSlideParts = Math.max(1, Math.ceil(bulletItems.length / itemsPerSlide));

    for (let part = 0; part < totalSlideParts; part++) {
      slideCounter++;
      const slide = ppt.addSlide();
      slide.background = { color: "FAF9F5" };

      // Top Consistent Accent Bar
      slide.addShape(ppt.ShapeType.rect, {
        x: 0.8, y: 0.5, w: 11.7, h: 0.08, fill: { color: "97422C" }
      });

      // Section Title with Part Suffix if split
      const displayTitle = totalSlideParts > 1
        ? `${idx + 1}. ${sec.title} (Part ${part + 1}/${totalSlideParts})`
        : `${idx + 1}. ${sec.title}`;

      slide.addText(displayTitle, {
        x: 0.8, y: 0.7, w: 11.5, h: 0.6,
        fontFace: "Georgia", fontSize: 20, color: "97422C", bold: true
      });

      slide.addText(`Core Brief: ${sec.brief}`, {
        x: 0.8, y: 1.3, w: 11.5, h: 0.35,
        fontFace: "Arial", fontSize: 12, color: "55423E", italic: true
      });

      // Card Container
      slide.addShape(ppt.ShapeType.rect, {
        x: 0.8, y: 1.8, w: 11.7, h: 4.8,
        fill: { color: "FFFFFF" }, line: { color: "DBC1BA", width: 1 }
      });

      // Chunk bullets for this slide
      const currentChunk = bulletItems.slice(part * itemsPerSlide, (part + 1) * itemsPerSlide);
      const textObjects = currentChunk.map((item) => ({
        text: item,
        options: {
          bullet: true,
          fontFace: "Arial",
          fontSize: 13,
          color: "1B1C1A",
          lineSpacing: 20,
          paraSpaceAfter: 12
        }
      }));

      slide.addText(textObjects, {
        x: 1.1, y: 2.0, w: 11.1, h: 4.3,
        valign: "top"
      });

      // Footer Slide Number
      slide.addText(`Paperrrrrr • Slide ${slideCounter}`, {
        x: 0.8, y: 6.8, w: 11.7, h: 0.3,
        fontFace: "Arial", fontSize: 10, color: "88726D", align: "right"
      });
    }
  });

  const buffer = (await ppt.stream()) as Buffer;
  return buffer;
}

// 3. Excel (.xlsx) Assembler
export async function assembleExcelSheet(input: AssembleDocumentInput): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Paperrrrrr";

  const sheet = workbook.addWorksheet("Document Synthesis", {
    views: [{ showGridLines: true }]
  });

  // Title Block (Columns A to F)
  sheet.mergeCells("A1:F1");
  const titleCell = sheet.getCell("A1");
  titleCell.value = input.title;
  titleCell.font = { name: "Georgia", size: 16, bold: true, color: { argb: "97422C" } };
  titleCell.alignment = { vertical: "middle", horizontal: "left" };

  sheet.mergeCells("A2:F2");
  const subCell = sheet.getCell("A2");
  subCell.value = `${input.subtitle} • Paperrrrrr Autonomous Studio`;
  subCell.font = { name: "Arial", size: 11, italic: true, color: { argb: "55423E" } };
  subCell.alignment = { vertical: "middle", horizontal: "left" };

  sheet.addRow([]);

  // Table Headers
  const headers = ["Index", "Section Title", "Brief & Scope", "Key Takeaway", "Growth / Score (%)", "Status"];
  const headerRow = sheet.addRow(headers);

  headerRow.eachCell((cell) => {
    cell.font = { name: "Arial", size: 11, bold: true, color: { argb: "FFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "97422C" } };
    cell.alignment = { vertical: "middle", horizontal: "center" };
    cell.border = {
      top: { style: "thin", color: { argb: "DBC1BA" } },
      bottom: { style: "medium", color: { argb: "97422C" } },
      left: { style: "thin", color: { argb: "DBC1BA" } },
      right: { style: "thin", color: { argb: "DBC1BA" } }
    };
  });

  // Data Rows with Typed Numeric Values
  input.sections.forEach((sec, idx) => {
    // Generate realistic percentage / metric for Excel formula computations
    const numericMetric = Math.min(0.99, 0.65 + (idx * 0.08));

    const row = sheet.addRow([
      idx + 1, // Real Number
      sec.title,
      sec.brief,
      sec.content ? sec.content.slice(0, 180).replace(/\[([^\]]+)\]\([^\)]+\)/g, "$1") + "..." : "Completed",
      numericMetric, // Real Typed Number for Excel formulas
      "Verified"
    ]);

    row.eachCell((cell, colIndex) => {
      cell.font = { name: "Arial", size: 10 };
      cell.border = {
        bottom: { style: "thin", color: { argb: "EFEEEA" } },
        left: { style: "thin", color: { argb: "EFEEEA" } },
        right: { style: "thin", color: { argb: "EFEEEA" } }
      };

      if (colIndex === 1) {
        cell.alignment = { horizontal: "center" };
        cell.numFmt = "0";
      } else if (colIndex === 5) {
        cell.alignment = { horizontal: "right" };
        cell.numFmt = "0.0%"; // Formatted as Excel percentage formula
        cell.font = { name: "Arial", size: 10, bold: true, color: { argb: "97422C" } };
      } else if (colIndex === 6) {
        cell.alignment = { horizontal: "center" };
        cell.font = { name: "Arial", size: 10, bold: true, color: { argb: "1B5E20" } };
      }
    });
  });

  // Dynamic Column Auto-Sizing based on real text content length
  sheet.columns.forEach((column) => {
    let maxLength = 12;
    if (column.eachCell) {
      column.eachCell({ includeEmpty: false }, (cell, rowNumber) => {
        if (rowNumber > 2) { // Exclude merged title rows
          const cellLen = cell.value ? String(cell.value).length : 0;
          if (cellLen > maxLength) {
            maxLength = Math.min(65, cellLen); // Cap at sane max width
          }
        }
      });
    }
    column.width = maxLength + 3;
  });

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

// 4. PDF (.pdf) Assembler
export async function assemblePdfDocument(input: AssembleDocumentInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: 54, // 0.75 inch clean margin
      size: "A4",
      bufferPages: true
    });
    const buffers: Buffer[] = [];

    doc.on("data", (chunk) => buffers.push(chunk));
    doc.on("end", () => {
      // Post-process page numbers on all buffered pages
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);

        // Running Header (Pages 2+)
        if (i > 0) {
          doc.fillColor("#88726D").font("Helvetica-Oblique").fontSize(8.5);
          doc.text("Paperrrrrr Document Studio", 54, 30, { align: "right", width: 487 });
          doc.moveTo(54, 44).lineTo(541, 44).strokeColor("#DBC1BA").lineWidth(0.5).stroke();
        }

        // Running Footer with Page Numbers (All Pages)
        doc.fillColor("#88726D").font("Helvetica").fontSize(8.5);
        doc.text(`Page ${i + 1} of ${range.count}`, 54, 790, { align: "right", width: 487 });
        doc.text("Paperrrrrr • Autonomous Research & Synthesis", 54, 790, { align: "left", width: 300 });
      }

      resolve(Buffer.concat(buffers));
    });
    doc.on("error", (err) => reject(err));

    // Cover / Title Page Block
    doc.fillColor("#97422C").font("Helvetica-Bold").fontSize(26).text(input.title, { align: "left", lineGap: 4 });
    doc.moveDown(0.3);

    doc.fillColor("#55423E").font("Helvetica-Oblique").fontSize(13).text(input.subtitle, { align: "left", lineGap: 2 });
    doc.moveDown(0.5);

    doc.fillColor("#88726D").font("Helvetica").fontSize(9.5).text(
      `Generated by Paperrrrrr • ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
      { align: "left" }
    );
    doc.moveDown(0.8);

    // Divider
    doc.moveTo(54, doc.y).lineTo(541, doc.y).strokeColor("#DBC1BA").lineWidth(1).stroke();
    doc.moveDown(1.2);

    // Sections with Smooth Page-Break Handling
    input.sections.forEach((sec, idx) => {
      // Check if heading fits on current page (leave at least 140pt)
      if (doc.y > 670) {
        doc.addPage();
      }

      doc.fillColor("#97422C").font("Helvetica-Bold").fontSize(16).text(
        `${idx + 1}. ${sec.title.replace(/^\d+\.\s*/, "")}`,
        { lineGap: 2 }
      );
      doc.moveDown(0.2);

      doc.fillColor("#55423E").font("Helvetica-Oblique").fontSize(10.5).text(`Scope: ${sec.brief}`, { lineGap: 2 });
      doc.moveDown(0.6);

      const paragraphs = (sec.content || sec.brief || "").split("\n\n");
      paragraphs.forEach((pText) => {
        if (!pText.trim()) return;

        // Clean link brackets for clean reading flow
        const formattedText = pText.replace(/\[([^\]]+)\]\((https?:\/\/[^\s\)]+)\)/g, "$1 ($2)");

        if (doc.y > 700) {
          doc.addPage();
        }

        doc.fillColor("#1B1C1A").font("Helvetica").fontSize(10.5).text(formattedText, {
          align: "justify",
          lineGap: 3.5,
          paragraphGap: 8
        });
      });

      doc.moveDown(1.0);
    });

    doc.end();
  });
}
