const path = require("path");
const pptxgen = require("pptxgenjs");

async function buildPowerPoint(outputFilename = "PaperLoop_Generated_Presentation.pptx") {
  console.log(`\n==================================================`);
  console.log(`📊 GENERATING EDITABLE POWERPOINT PRESENTATION (.pptx)`);
  console.log(`==================================================\n`);

  const ppt = new pptxgen();
  ppt.layout = "LAYOUT_16x9";
  ppt.title = "Renewable Energy Adoption in India";

  // Slide 1: Title Slide (Terracotta & Off-white layout)
  const slide1 = ppt.addSlide();
  slide1.background = { color: "FAF9F5" }; // Warm paper background
  
  slide1.addShape(ppt.ShapeType.rect, {
    x: 0.8, y: 1.0, w: 11.7, h: 0.1, fill: { color: "97422C" }
  });

  slide1.addText("Renewable Energy Adoption in India", {
    x: 0.8, y: 1.8, w: 11.5, h: 1.5,
    fontFace: "Georgia", fontSize: 36, color: "97422C", bold: true
  });

  slide1.addText("A Strategic Comparison & Analysis of 2030 Non-Fossil Targets", {
    x: 0.8, y: 3.2, w: 11.5, h: 0.8,
    fontFace: "Arial", fontSize: 20, color: "55423E", italic: true
  });

  slide1.addText("Generated by PaperLoop Document Studio", {
    x: 0.8, y: 5.5, w: 8.0, h: 0.5,
    fontFace: "Arial", fontSize: 14, color: "88726D"
  });

  // Slide 2: Executive Summary Cards
  const slide2 = ppt.addSlide();
  slide2.background = { color: "FAF9F5" };
  
  slide2.addText("Executive Summary: Current Baseline", {
    x: 0.8, y: 0.6, w: 11.0, h: 0.8,
    fontFace: "Georgia", fontSize: 26, color: "97422C", bold: true
  });

  // Card 1
  slide2.addShape(ppt.ShapeType.rect, {
    x: 0.8, y: 1.6, w: 3.6, h: 4.5,
    fill: { color: "FFFFFF" }, line: { color: "DBC1BA", width: 1 }
  });
  slide2.addText("4th Globally", {
    x: 1.0, y: 1.9, w: 3.2, h: 0.6,
    fontFace: "Georgia", fontSize: 22, color: "97422C", bold: true
  });
  slide2.addText("India stands 4th globally in installed renewable capacity with rapid solar & wind acceleration.", {
    x: 1.0, y: 2.6, w: 3.2, h: 3.0,
    fontFace: "Arial", fontSize: 14, color: "1B1C1A"
  });

  // Card 2
  slide2.addShape(ppt.ShapeType.rect, {
    x: 4.8, y: 1.6, w: 3.6, h: 4.5,
    fill: { color: "FFFFFF" }, line: { color: "DBC1BA", width: 1 }
  });
  slide2.addText("500 GW Target", {
    x: 5.0, y: 1.9, w: 3.2, h: 0.6,
    fontFace: "Georgia", fontSize: 22, color: "97422C", bold: true
  });
  slide2.addText("Aiming for 500 GW non-fossil capacity by 2030, covering 50% of total electricity needs.", {
    x: 5.0, y: 2.6, w: 3.2, h: 3.0,
    fontFace: "Arial", fontSize: 14, color: "1B1C1A"
  });

  // Card 3
  slide2.addShape(ppt.ShapeType.rect, {
    x: 8.8, y: 1.6, w: 3.6, h: 4.5,
    fill: { color: "FFFFFF" }, line: { color: "DBC1BA", width: 1 }
  });
  slide2.addText("PLI & KUSUM", {
    x: 9.0, y: 1.9, w: 3.2, h: 0.6,
    fontFace: "Georgia", fontSize: 22, color: "97422C", bold: true
  });
  slide2.addText("Production-linked incentives and solar feeder pumps drive domestic manufacturing & rural solarization.", {
    x: 9.0, y: 2.6, w: 3.2, h: 3.0,
    fontFace: "Arial", fontSize: 14, color: "1B1C1A"
  });

  const outputPath = path.join(__dirname, outputFilename);
  await ppt.writeFile({ fileName: outputPath });
  console.log(`✅ PowerPoint presentation successfully generated!`);
  console.log(`File saved to: ${outputPath}`);
}

buildPowerPoint();
