const fs = require("fs");
const path = require("path");
const docx = require("docx");

const {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  TableOfContents,
  Header,
  Footer,
  PageNumber,
  NumberFormat,
  AlignmentType,
  BorderStyle,
  convertInchesToTwip
} = docx;

// Sample full document data (combining Stage 1 research + Stage 2 outline + Stage 3 sections)
const documentData = {
  title: "Renewable Energy Adoption in India: Current Landscape, Policy Drivers, and Future Trajectory",
  subtitle: "A Comprehensive Analysis of Solar, Wind, and Green Hydrogen Integration by 2030",
  author: "PaperLoop Document Studio",
  sections: [
    {
      title: "1. Executive Summary & Current Renewable Energy Baseline",
      content: `India has emerged as one of the fastest-growing renewable energy markets globally, currently holding the 4th position worldwide in total installed renewable capacity. As of recent ministry updates, the nation's solar power infrastructure has scaled beyond 70 GW, while onshore wind installed capacity has surpassed 44 GW.\n\nThis rapid acceleration forms part of a broader geopolitical and environmental commitment to achieve 500 GW of non-fossil fuel power capacity by 2030, fulfilling half of the national electricity demand through clean energy sources. Strategic interventions such as the Production Linked Incentive (PLI) scheme for high-efficiency solar photovoltaic modules have significantly reduced reliance on imported equipment, establishing domestic supply chains and underpinning long-term energy independence.`
    },
    {
      title: "2. Policy Frameworks: PLI Schemes and PM-KUSUM",
      content: `The policy architecture governing India's green energy transition is built around targeted economic incentives and decentralized rural deployment. A major catalyst is the Production Linked Incentive (PLI) scheme, designed to stimulate gigawatt-scale domestic manufacturing of high-efficiency solar cells and modules.\n\nConcurrently, the PM-KUSUM (Pradhan Mantri Kisan Urja Suraksha evam Utthaan Mahabhiyan) initiative focuses on solarizing agricultural pumps and decentralized solar plants in rural feeder systems. By decoupling agricultural electricity subsidies from state power distribution companies (discoms), PM-KUSUM enhances farmers' financial stability while injecting clean power directly into local feeder networks.`
    },
    {
      title: "3. Emerging Vectors: National Green Hydrogen Mission",
      content: `As India advances toward its 2030 targets, the National Green Hydrogen Mission represents a decisive step toward industrial decarbonization. The program targets the production of at least 5 million metric tonnes (MMT) of green hydrogen per annum by 2030, requiring an incremental 125 GW of dedicated renewable generation capacity.\n\nAchieving these milestones demands addressing critical grid integration bottlenecks, scaling battery energy storage systems (BESS), and resolving state discom financial liquidity challenges.`
    },
    {
      title: "4. Strategic Roadmap & Conclusion",
      content: `In conclusion, India's renewable energy trajectory balances ambitious federal targets with technical and economic challenges. Continued investment in grid modernization, pumped hydro storage, and discom reform will ensure that the 500 GW goal by 2030 is achieved reliably and sustainably.`
    }
  ]
};

async function buildWordDocument(data, outputFilename = "PaperLoop_Generated_Report.docx") {
  console.log(`\n==================================================`);
  console.log(`📄 STAGE 4: ASSEMBLING EDITABLE WORD DOCUMENT (.docx)`);
  console.log(`Title: "${data.title}"`);
  console.log(`Number of Sections: ${data.sections.length}`);
  console.log(`==================================================\n`);

  const docParagraphs = [];

  // 1. Cover Title Page
  docParagraphs.push(
    new Paragraph({
      text: data.title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.LEFT,
      spacing: { before: 400, after: 200 }
    }),
    new Paragraph({
      text: data.subtitle,
      heading: HeadingLevel.SUBTITLE,
      alignment: AlignmentType.LEFT,
      spacing: { after: 600 }
    }),
    new Paragraph({
      children: [
        new TextRun({ text: "Generated by: ", bold: true, color: "55423E" }),
        new TextRun({ text: data.author, italic: true, color: "97422C" }),
        new TextRun({ text: " | Date: ", bold: true, color: "55423E" }),
        new TextRun({ text: new Date().toLocaleDateString("en-US", { year: 'numeric', month: 'long', day: 'numeric' }) })
      ],
      spacing: { after: 800 }
    }),
    
    // Horizontal Rule Divider
    new Paragraph({
      border: { bottom: { color: "DBC1BA", space: 1, style: BorderStyle.SINGLE, size: 6 } },
      spacing: { after: 400 }
    }),

    // 2. Table of Contents Section Header
    new Paragraph({
      text: "Table of Contents",
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 200, after: 200 }
    }),

    // Native Word Table of Contents field
    new TableOfContents("Table of Contents", {
      hyperlink: true,
      headingStyleRange: "1-3"
    }),

    new Paragraph({
      spacing: { after: 600 }
    })
  );

  // 3. Document Body Sections
  data.sections.forEach((sec) => {
    // Section Heading (Heading 1 style)
    docParagraphs.push(
      new Paragraph({
        text: sec.title,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 }
      })
    );

    // Section Paragraphs
    const paragraphs = sec.content.split("\n\n");
    paragraphs.forEach((pText) => {
      docParagraphs.push(
        new Paragraph({
          children: [
            new TextRun({
              text: pText,
              size: 24, // 12pt
              font: "Plus Jakarta Sans"
            })
          ],
          spacing: { after: 200, line: 360 } // 1.5 line spacing
        })
      );
    });
  });

  // Create Document with PaperLoop typography styles & margins
  const doc = new Document({
    creator: "PaperLoop Document Studio",
    title: data.title,
    description: data.subtitle,
    styles: {
      default: {
        document: {
          run: {
            font: "Plus Jakarta Sans",
            color: "1B1C1A"
          }
        }
      },
      paragraphStyles: [
        {
          id: "Title",
          name: "Title",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: {
            font: "Georgia",
            size: 52, // 26pt
            bold: true,
            color: "97422C" // PaperLoop Terracotta primary
          }
        },
        {
          id: "Subtitle",
          name: "Subtitle",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: {
            font: "Plus Jakarta Sans",
            size: 28, // 14pt
            italic: true,
            color: "55423E"
          }
        },
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: {
            font: "Georgia",
            size: 36, // 18pt
            bold: true,
            color: "97422C"
          }
        }
      ]
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: convertInchesToTwip(1),
              bottom: convertInchesToTwip(1),
              left: convertInchesToTwip(1),
              right: convertInchesToTwip(1)
            }
          }
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                text: "PaperLoop Document Studio — Research Report",
                alignment: AlignmentType.RIGHT,
                style: "Subtitle"
              })
            ]
          })
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun("Page "),
                  new TextRun({
                    children: [PageNumber.CURRENT]
                  }),
                  new TextRun(" of "),
                  new TextRun({
                    children: [PageNumber.TOTAL_PAGES]
                  })
                ]
              })
            ]
          })
        },
        children: docParagraphs
      }
    ]
  });

  const outputPath = path.join(__dirname, outputFilename);
  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync(outputPath, buffer);

  console.log(`✅ Word document successfully generated!`);
  console.log(`File saved to: ${outputPath}`);
  console.log(`File size: ${(buffer.length / 1024).toFixed(2)} KB`);
  return outputPath;
}

buildWordDocument(documentData);
